// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/supuwoerc/gapi-server/internal/dal/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newCronJobExecution(db *gorm.DB, opts ...gen.DOOption) cronJobExecution {
	_cronJobExecution := cronJobExecution{}

	_cronJobExecution.cronJobExecutionDo.UseDB(db, opts...)
	_cronJobExecution.cronJobExecutionDo.UseModel(&model.CronJobExecution{})

	tableName := _cronJobExecution.cronJobExecutionDo.TableName()
	_cronJobExecution.ALL = field.NewAsterisk(tableName)
	_cronJobExecution.ID = field.NewUint64(tableName, "id")
	_cronJobExecution.JobName = field.NewString(tableName, "job_name")
	_cronJobExecution.Status = field.NewString(tableName, "status")
	_cronJobExecution.StartedAt = field.NewTime(tableName, "started_at")
	_cronJobExecution.EndedAt = field.NewTime(tableName, "ended_at")
	_cronJobExecution.Duration = field.NewInt64(tableName, "duration")
	_cronJobExecution.Error = field.NewString(tableName, "error")
	_cronJobExecution.TriggeredBy = field.NewString(tableName, "triggered_by")
	_cronJobExecution.CreatedAt = field.NewTime(tableName, "created_at")
	_cronJobExecution.UpdatedAt = field.NewTime(tableName, "updated_at")
	_cronJobExecution.DeletedAt = field.NewUint64(tableName, "deleted_at")

	_cronJobExecution.fillFieldMap()

	return _cronJobExecution
}

// cronJobExecution 定时任务执行日志
type cronJobExecution struct {
	cronJobExecutionDo cronJobExecutionDo

	ALL         field.Asterisk
	ID          field.Uint64
	JobName     field.String // 任务名称
	Status      field.String // 执行状态(running/success/failed/cancelled/panic)
	StartedAt   field.Time   // 开始时间
	EndedAt     field.Time   // 结束时间
	Duration    field.Int64  // 耗时（毫秒）
	Error       field.String // 错误信息
	TriggeredBy field.String // 触发方式(scheduler/manual)
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Uint64

	fieldMap map[string]field.Expr
}

func (c cronJobExecution) Table(newTableName string) *cronJobExecution {
	c.cronJobExecutionDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cronJobExecution) As(alias string) *cronJobExecution {
	c.cronJobExecutionDo.DO = *(c.cronJobExecutionDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cronJobExecution) updateTableName(table string) *cronJobExecution {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint64(table, "id")
	c.JobName = field.NewString(table, "job_name")
	c.Status = field.NewString(table, "status")
	c.StartedAt = field.NewTime(table, "started_at")
	c.EndedAt = field.NewTime(table, "ended_at")
	c.Duration = field.NewInt64(table, "duration")
	c.Error = field.NewString(table, "error")
	c.TriggeredBy = field.NewString(table, "triggered_by")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewUint64(table, "deleted_at")

	c.fillFieldMap()

	return c
}

func (c *cronJobExecution) WithContext(ctx context.Context) ICronJobExecutionDo {
	return c.cronJobExecutionDo.WithContext(ctx)
}

func (c cronJobExecution) TableName() string { return c.cronJobExecutionDo.TableName() }

func (c cronJobExecution) Alias() string { return c.cronJobExecutionDo.Alias() }

func (c cronJobExecution) Columns(cols ...field.Expr) gen.Columns {
	return c.cronJobExecutionDo.Columns(cols...)
}

func (c *cronJobExecution) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cronJobExecution) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 11)
	c.fieldMap["id"] = c.ID
	c.fieldMap["job_name"] = c.JobName
	c.fieldMap["status"] = c.Status
	c.fieldMap["started_at"] = c.StartedAt
	c.fieldMap["ended_at"] = c.EndedAt
	c.fieldMap["duration"] = c.Duration
	c.fieldMap["error"] = c.Error
	c.fieldMap["triggered_by"] = c.TriggeredBy
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
}

func (c cronJobExecution) clone(db *gorm.DB) cronJobExecution {
	c.cronJobExecutionDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cronJobExecution) replaceDB(db *gorm.DB) cronJobExecution {
	c.cronJobExecutionDo.ReplaceDB(db)
	return c
}

type cronJobExecutionDo struct{ gen.DO }

type ICronJobExecutionDo interface {
	gen.SubQuery
	Debug() ICronJobExecutionDo
	WithContext(ctx context.Context) ICronJobExecutionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICronJobExecutionDo
	WriteDB() ICronJobExecutionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICronJobExecutionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICronJobExecutionDo
	Not(conds ...gen.Condition) ICronJobExecutionDo
	Or(conds ...gen.Condition) ICronJobExecutionDo
	Select(conds ...field.Expr) ICronJobExecutionDo
	Where(conds ...gen.Condition) ICronJobExecutionDo
	Order(conds ...field.Expr) ICronJobExecutionDo
	Distinct(cols ...field.Expr) ICronJobExecutionDo
	Omit(cols ...field.Expr) ICronJobExecutionDo
	Join(table schema.Tabler, on ...field.Expr) ICronJobExecutionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICronJobExecutionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICronJobExecutionDo
	Group(cols ...field.Expr) ICronJobExecutionDo
	Having(conds ...gen.Condition) ICronJobExecutionDo
	Limit(limit int) ICronJobExecutionDo
	Offset(offset int) ICronJobExecutionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICronJobExecutionDo
	Unscoped() ICronJobExecutionDo
	Create(values ...*model.CronJobExecution) error
	CreateInBatches(values []*model.CronJobExecution, batchSize int) error
	Save(values ...*model.CronJobExecution) error
	First() (*model.CronJobExecution, error)
	Take() (*model.CronJobExecution, error)
	Last() (*model.CronJobExecution, error)
	Find() ([]*model.CronJobExecution, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CronJobExecution, err error)
	FindInBatches(result *[]*model.CronJobExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CronJobExecution) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICronJobExecutionDo
	Assign(attrs ...field.AssignExpr) ICronJobExecutionDo
	Joins(fields ...field.RelationField) ICronJobExecutionDo
	Preload(fields ...field.RelationField) ICronJobExecutionDo
	FirstOrInit() (*model.CronJobExecution, error)
	FirstOrCreate() (*model.CronJobExecution, error)
	FindByPage(offset int, limit int) (result []*model.CronJobExecution, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICronJobExecutionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cronJobExecutionDo) Debug() ICronJobExecutionDo {
	return c.withDO(c.DO.Debug())
}

func (c cronJobExecutionDo) WithContext(ctx context.Context) ICronJobExecutionDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cronJobExecutionDo) ReadDB() ICronJobExecutionDo {
	return c.Clauses(dbresolver.Read)
}

func (c cronJobExecutionDo) WriteDB() ICronJobExecutionDo {
	return c.Clauses(dbresolver.Write)
}

func (c cronJobExecutionDo) Session(config *gorm.Session) ICronJobExecutionDo {
	return c.withDO(c.DO.Session(config))
}

func (c cronJobExecutionDo) Clauses(conds ...clause.Expression) ICronJobExecutionDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cronJobExecutionDo) Returning(value interface{}, columns ...string) ICronJobExecutionDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cronJobExecutionDo) Not(conds ...gen.Condition) ICronJobExecutionDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cronJobExecutionDo) Or(conds ...gen.Condition) ICronJobExecutionDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cronJobExecutionDo) Select(conds ...field.Expr) ICronJobExecutionDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cronJobExecutionDo) Where(conds ...gen.Condition) ICronJobExecutionDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cronJobExecutionDo) Order(conds ...field.Expr) ICronJobExecutionDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cronJobExecutionDo) Distinct(cols ...field.Expr) ICronJobExecutionDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cronJobExecutionDo) Omit(cols ...field.Expr) ICronJobExecutionDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cronJobExecutionDo) Join(table schema.Tabler, on ...field.Expr) ICronJobExecutionDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cronJobExecutionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICronJobExecutionDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cronJobExecutionDo) RightJoin(table schema.Tabler, on ...field.Expr) ICronJobExecutionDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cronJobExecutionDo) Group(cols ...field.Expr) ICronJobExecutionDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cronJobExecutionDo) Having(conds ...gen.Condition) ICronJobExecutionDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cronJobExecutionDo) Limit(limit int) ICronJobExecutionDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cronJobExecutionDo) Offset(offset int) ICronJobExecutionDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cronJobExecutionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICronJobExecutionDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cronJobExecutionDo) Unscoped() ICronJobExecutionDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cronJobExecutionDo) Create(values ...*model.CronJobExecution) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cronJobExecutionDo) CreateInBatches(values []*model.CronJobExecution, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cronJobExecutionDo) Save(values ...*model.CronJobExecution) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cronJobExecutionDo) First() (*model.CronJobExecution, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CronJobExecution), nil
	}
}

func (c cronJobExecutionDo) Take() (*model.CronJobExecution, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CronJobExecution), nil
	}
}

func (c cronJobExecutionDo) Last() (*model.CronJobExecution, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CronJobExecution), nil
	}
}

func (c cronJobExecutionDo) Find() ([]*model.CronJobExecution, error) {
	result, err := c.DO.Find()
	return result.([]*model.CronJobExecution), err
}

func (c cronJobExecutionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CronJobExecution, err error) {
	buf := make([]*model.CronJobExecution, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cronJobExecutionDo) FindInBatches(result *[]*model.CronJobExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cronJobExecutionDo) Attrs(attrs ...field.AssignExpr) ICronJobExecutionDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cronJobExecutionDo) Assign(attrs ...field.AssignExpr) ICronJobExecutionDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cronJobExecutionDo) Joins(fields ...field.RelationField) ICronJobExecutionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cronJobExecutionDo) Preload(fields ...field.RelationField) ICronJobExecutionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cronJobExecutionDo) FirstOrInit() (*model.CronJobExecution, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CronJobExecution), nil
	}
}

func (c cronJobExecutionDo) FirstOrCreate() (*model.CronJobExecution, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CronJobExecution), nil
	}
}

func (c cronJobExecutionDo) FindByPage(offset int, limit int) (result []*model.CronJobExecution, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cronJobExecutionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cronJobExecutionDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cronJobExecutionDo) Delete(models ...*model.CronJobExecution) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cronJobExecutionDo) withDO(do gen.Dao) *cronJobExecutionDo {
	c.DO = *do.(*gen.DO)
	return c
}
