// Code generated by "stringer -type=ResourceType -linecomment -output resource_type_string.go"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResourceTypeAPI-1]
	_ = x[ResourceTypeFrontendMenu-2]
	_ = x[ResourceTypeFrontendRoute-3]
	_ = x[ResourceTypeFrontendButton-4]
	_ = x[ResourceTypeData-5]
}

const _ResourceType_name = "apifrontend-menufrontend-routefrontend-buttondata"

var _ResourceType_index = [...]uint8{0, 3, 16, 30, 45, 49}

func (i ResourceType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ResourceType_index)-1 {
		return "ResourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResourceType_name[_ResourceType_index[idx]:_ResourceType_index[idx+1]]
}
