// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNamePermission = "sys_permission"

// Permission 权限表
type Permission struct {
	ID           uint64                `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Code         string                `gorm:"column:code;type:varchar(128);not null;uniqueIndex:idx_code,priority:1;comment:权限标识 eg:user:create" json:"code"`                        // 权限标识 eg:user:create
	Name         string                `gorm:"column:name;type:varchar(128);not null;comment:权限显示名称" json:"name"`                                                                     // 权限显示名称
	ResourceType string                `gorm:"column:resource_type;type:varchar(32);not null;index:idx_resource_type,priority:1;comment:资源类型 api/data/frontend" json:"resource_type"` // 资源类型 api/data/frontend
	ResourcePath string                `gorm:"column:resource_path;type:varchar(256);not null;comment:资源路径" json:"resource_path"`                                                     // 资源路径
	Action       string                `gorm:"column:action;type:varchar(32);not null;comment:操作 create/read/update/delete" json:"action"`                                            // 操作 create/read/update/delete
	Description  string                `gorm:"column:description;type:varchar(256);not null;comment:权限描述" json:"description"`                                                         // 权限描述
	CreatedAt    time.Time             `gorm:"column:created_at;type:datetime;not null" json:"created_at"`
	UpdatedAt    time.Time             `gorm:"column:updated_at;type:datetime;not null" json:"updated_at"`
	DeletedAt    soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint unsigned;not null;index;softDelete:milli" json:"deleted_at,omitempty"`
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
