// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameRolePermission = "sys_role_permission"

// RolePermission 角色权限关联表
type RolePermission struct {
	ID           uint64                `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	RoleID       uint64                `gorm:"column:role_id;type:bigint unsigned;not null;uniqueIndex:uk_role_perm,priority:1;comment:角色ID" json:"role_id"`                                                // 角色ID
	PermissionID uint64                `gorm:"column:permission_id;type:bigint unsigned;not null;uniqueIndex:uk_role_perm,priority:2;index:idx_permission_id,priority:1;comment:权限ID" json:"permission_id"` // 权限ID
	Effect       PermissionEffect      `gorm:"column:effect;type:varchar(8);not null;default:allow;comment:效果 allow/deny" json:"effect"`                                                                    // 效果 allow/deny
	CreatedAt    time.Time             `gorm:"column:created_at;type:datetime;not null" json:"created_at"`
	UpdatedAt    time.Time             `gorm:"column:updated_at;type:datetime;not null" json:"updated_at"`
	DeletedAt    soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint unsigned;not null;uniqueIndex:uk_role_perm,priority:3;index;softDelete:milli" json:"deleted_at,omitempty"`
}

// TableName RolePermission's table name
func (*RolePermission) TableName() string {
	return TableNameRolePermission
}
