// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameCronJob = "sys_cron_job"

// CronJob mapped from table <sys_cron_job>
type CronJob struct {
	ID          int64                 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name        string                `gorm:"column:name;type:character varying(128);not null;uniqueIndex:idx_cron_job_name,priority:1;comment:任务唯一标识" json:"name"` // 任务唯一标识
	Description *string               `gorm:"column:description;type:character varying(512);comment:任务描述" json:"description"`                                       // 任务描述
	Interval    string                `gorm:"column:interval;type:character varying(64);not null;comment:cron 表达式（6位含秒）" json:"interval"`                           // cron 表达式（6位含秒）
	Enabled     bool                  `gorm:"column:enabled;type:boolean;not null;default:true;comment:是否启用" json:"enabled"`                                        // 是否启用
	LastRunAt   *time.Time            `gorm:"column:last_run_at;type:timestamp with time zone;comment:最近一次执行时间" json:"last_run_at"`                                 // 最近一次执行时间
	LastStatus  *string               `gorm:"column:last_status;type:character varying(16);comment:最近一次执行状态, NULL 表示从未执行" json:"last_status"`                       // 最近一次执行状态, NULL 表示从未执行
	CreatedAt   time.Time             `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time             `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt   soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint;not null;index;softDelete:milli" json:"deleted_at,omitempty"`
}

// TableName CronJob's table name
func (*CronJob) TableName() string {
	return TableNameCronJob
}
