// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/plugin/soft_delete"
)

const TableNameUser = "sys_user"

// User mapped from table <sys_user>
type User struct {
	ID             int64                       `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Username       string                      `gorm:"column:username;type:character varying(64);not null;uniqueIndex:idx_user_username,priority:1;comment:登录名" json:"username"` // 登录名
	PasswordHash   string                      `gorm:"column:password_hash;type:character varying(256);not null;comment:密码哈希" json:"-"`                                          // 密码哈希
	Email          string                      `gorm:"column:email;type:character varying(128);not null;uniqueIndex:idx_user_email,priority:1;comment:邮箱" json:"email"`          // 邮箱
	Phone          string                      `gorm:"column:phone;type:character varying(32);not null;comment:手机号" json:"phone"`                                                // 手机号
	Avatar         string                      `gorm:"column:avatar;type:character varying(512);not null;comment:头像URL" json:"avatar"`                                           // 头像URL
	Bio            string                      `gorm:"column:bio;type:character varying(256);not null;comment:个人简介" json:"bio"`                                                  // 个人简介
	Enabled        bool                        `gorm:"column:enabled;type:boolean;not null;default:true;comment:是否启用" json:"enabled"`                                            // 是否启用
	LastLoginAt    *time.Time                  `gorm:"column:last_login_at;type:timestamp with time zone;comment:最近登录时间" json:"last_login_at"`                                   // 最近登录时间
	LoginFailCount int32                       `gorm:"column:login_fail_count;type:integer;not null;comment:连续登录失败次数" json:"login_fail_count"`                                   // 连续登录失败次数
	LockedUntil    *time.Time                  `gorm:"column:locked_until;type:timestamp with time zone;comment:锁定截止时间" json:"locked_until"`                                     // 锁定截止时间
	CompletedTours datatypes.JSONSlice[string] `gorm:"column:completed_tours;type:jsonb;comment:已完成的引导" json:"completed_tours"`                                                  // 已完成的引导
	CreatedAt      time.Time                   `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt      time.Time                   `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt      soft_delete.DeletedAt       `gorm:"column:deleted_at;type:bigint;not null;index;softDelete:milli" json:"deleted_at,omitempty"`
	Roles          []Role                      `gorm:"many2many:sys_user_role" json:"roles"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
