// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameCronJobExecution = "sys_cron_job_execution"

// CronJobExecution 定时任务执行日志
type CronJobExecution struct {
	ID          uint64                `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	JobName     string                `gorm:"column:job_name;type:varchar(128);not null;index:idx_job_name,priority:1;comment:任务名称" json:"job_name"`              // 任务名称
	Status      string                `gorm:"column:status;type:varchar(16);not null;comment:执行状态(running/success/failed/cancelled/panic)" json:"status"`         // 执行状态(running/success/failed/cancelled/panic)
	StartedAt   time.Time             `gorm:"column:started_at;type:datetime;not null;comment:开始时间" json:"started_at"`                                            // 开始时间
	EndedAt     *time.Time            `gorm:"column:ended_at;type:datetime;comment:结束时间" json:"ended_at"`                                                         // 结束时间
	Duration    *int64                `gorm:"column:duration;type:bigint;comment:耗时（毫秒）" json:"duration"`                                                         // 耗时（毫秒）
	Error       string                `gorm:"column:error;type:text;not null;comment:错误信息" json:"error"`                                                          // 错误信息
	TriggeredBy TriggeredBy           `gorm:"column:triggered_by;type:varchar(32);not null;default:scheduler;comment:触发方式(scheduler/manual)" json:"triggered_by"` // 触发方式(scheduler/manual)
	CreatedAt   time.Time             `gorm:"column:created_at;type:datetime;not null" json:"created_at"`
	UpdatedAt   time.Time             `gorm:"column:updated_at;type:datetime;not null" json:"updated_at"`
	DeletedAt   soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint unsigned;not null;index;softDelete:milli" json:"deleted_at,omitempty"`
}

// TableName CronJobExecution's table name
func (*CronJobExecution) TableName() string {
	return TableNameCronJobExecution
}
