// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameCronJobExecution = "sys_cron_job_execution"

// CronJobExecution mapped from table <sys_cron_job_execution>
type CronJobExecution struct {
	ID          int64                 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_execution_job_name_id,priority:1" json:"id"`
	JobName     string                `gorm:"column:job_name;type:character varying(128);not null;index:idx_execution_job_name_id,priority:2;comment:任务名称" json:"job_name"` // 任务名称
	Status      string                `gorm:"column:status;type:character varying(16);not null;comment:执行状态(running/success/failed/cancelled/panic)" json:"status"`         // 执行状态(running/success/failed/cancelled/panic)
	StartedAt   time.Time             `gorm:"column:started_at;type:timestamp with time zone;not null;comment:开始时间" json:"started_at"`                                      // 开始时间
	EndedAt     *time.Time            `gorm:"column:ended_at;type:timestamp with time zone;comment:结束时间" json:"ended_at"`                                                   // 结束时间
	Duration    *int64                `gorm:"column:duration;type:bigint;comment:耗时（毫秒）" json:"duration"`                                                                   // 耗时（毫秒）
	Error       string                `gorm:"column:error;type:text;not null;comment:错误信息" json:"error"`                                                                    // 错误信息
	TriggeredBy TriggeredBy           `gorm:"column:triggered_by;type:character varying(32);not null;default:scheduler;comment:触发方式(scheduler/manual)" json:"triggered_by"` // 触发方式(scheduler/manual)
	CreatedAt   time.Time             `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time             `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt   soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint;not null;index;softDelete:milli" json:"deleted_at,omitempty"`
}

// TableName CronJobExecution's table name
func (*CronJobExecution) TableName() string {
	return TableNameCronJobExecution
}
