// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameRole = "sys_role"

// Role 角色表
type Role struct {
	ID          uint64                `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name        string                `gorm:"column:name;type:varchar(64);not null;comment:角色显示名称" json:"name"`                                    // 角色显示名称
	Code        string                `gorm:"column:code;type:varchar(64);not null;uniqueIndex:idx_code,priority:1;comment:角色唯一标识" json:"code"`    // 角色唯一标识
	ParentID    *uint64               `gorm:"column:parent_id;type:bigint unsigned;index:idx_parent_id,priority:1;comment:父角色ID" json:"parent_id"` // 父角色ID
	Description string                `gorm:"column:description;type:varchar(256);not null;comment:角色描述" json:"description"`                       // 角色描述
	SortOrder   int32                 `gorm:"column:sort_order;type:int;not null;comment:排序" json:"sort_order"`                                    // 排序
	Status      int32                 `gorm:"column:status;type:tinyint;not null;default:1;comment:状态 1=启用 0=禁用" json:"status"`                    // 状态 1=启用 0=禁用
	CreatedAt   time.Time             `gorm:"column:created_at;type:datetime;not null" json:"created_at"`
	UpdatedAt   time.Time             `gorm:"column:updated_at;type:datetime;not null" json:"updated_at"`
	DeletedAt   soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint unsigned;not null;index;softDelete:milli" json:"deleted_at,omitempty"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
