// Code generated by "stringer -type=StatusCode -linecomment -output code_string.go"; DO NOT EDIT.

package response

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ok-10000]
	_ = x[Error-10001]
	_ = x[InvalidParams-10002]
	_ = x[InvalidToken-10003]
	_ = x[CancelRequest-10004]
	_ = x[RecoveryError-10005]
	_ = x[InternalError-10006]
	_ = x[TimeoutErr-10007]
	_ = x[Busy-10008]
}

const _StatusCode_name = "okerrorinvalidParamsinvalidTokencancelRequestrecoveryErrorinternalErrortimeoutErrbusy"

var _StatusCode_index = [...]uint8{0, 2, 7, 20, 32, 45, 58, 71, 81, 85}

func (i StatusCode) String() string {
	idx := int(i) - 10000
	if i < 10000 || idx >= len(_StatusCode_index)-1 {
		return "StatusCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatusCode_name[_StatusCode_index[idx]:_StatusCode_index[idx+1]]
}
