// Code generated by "stringer -type=StatusCode -linecomment -output code_string.go"; DO NOT EDIT.

package response

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ok-10000]
	_ = x[Error-10001]
	_ = x[InvalidParams-10002]
	_ = x[InvalidToken-10003]
	_ = x[CancelRequest-10004]
	_ = x[RecoveryError-10005]
	_ = x[InternalError-10006]
	_ = x[TimeoutErr-10007]
	_ = x[Busy-10008]
	_ = x[UserAlreadyExists-20001]
	_ = x[InvalidCredential-20002]
	_ = x[UserDisabled-20003]
	_ = x[UserLocked-20004]
	_ = x[TokenExpired-20005]
	_ = x[RefreshTokenUsed-20006]
}

const (
	_StatusCode_name_0 = "okerrorinvalidParamsinvalidTokencancelRequestrecoveryErrorinternalErrortimeoutErrbusy"
	_StatusCode_name_1 = "userAlreadyExistsinvalidCredentialuserDisableduserLockedtokenExpiredrefreshTokenUsed"
)

var (
	_StatusCode_index_0 = [...]uint8{0, 2, 7, 20, 32, 45, 58, 71, 81, 85}
	_StatusCode_index_1 = [...]uint8{0, 17, 34, 46, 56, 68, 84}
)

func (i StatusCode) String() string {
	switch {
	case 10000 <= i && i <= 10008:
		i -= 10000
		return _StatusCode_name_0[_StatusCode_index_0[i]:_StatusCode_index_0[i+1]]
	case 20001 <= i && i <= 20006:
		i -= 20001
		return _StatusCode_name_1[_StatusCode_index_1[i]:_StatusCode_index_1[i+1]]
	default:
		return "StatusCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
