// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/supuwoerc/gapi-server/internal/app"
	"github.com/supuwoerc/gapi-server/internal/config"
	"github.com/supuwoerc/gapi-server/internal/cronjob"
	"github.com/supuwoerc/gapi-server/internal/handler/v1"
	"github.com/supuwoerc/gapi-server/internal/provider"
	"github.com/supuwoerc/gapi-server/internal/repository"
	"github.com/supuwoerc/gapi-server/internal/router"
	"github.com/supuwoerc/gapi-server/internal/server"
	"github.com/supuwoerc/gapi-server/internal/service"
	"github.com/supuwoerc/gapi-server/pkg/database"
	"github.com/supuwoerc/gapi-server/pkg/etcd"
	"github.com/supuwoerc/gapi-server/pkg/logger"
	"github.com/supuwoerc/gapi-server/pkg/redis"
)

import (
	_ "github.com/supuwoerc/gapi-server/docs"
)

// Injectors from wire.go:

func WireApp() (*app.App, error) {
	viper := config.NewViper()
	configConfig := config.NewConfig(viper)
	serverConfig := provider.ProvideServerConfig(configConfig)
	logConfig := provider.ProvideLogConfig(configConfig)
	loggerLogger := logger.NewLogger(logConfig)
	redisConfig := provider.ProvideRedisConfig(configConfig)
	client, err := redis.NewClient(redisConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	healthHandler := v1.NewHealthHandler(loggerLogger)
	databaseConfig := provider.ProvideDBConfig(configConfig)
	db, err := database.NewConnection(databaseConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	cronJobRepository := repository.NewCronJobRepository(db)
	cronJobService := service.NewCronJobService(cronJobRepository, loggerLogger)
	cronConfig := provider.ProvideCronConfig(configConfig)
	v := provider.ProvideSystemJobs(loggerLogger)
	jobManager := cronjob.NewJobManager(loggerLogger, cronJobService, cronConfig, v)
	cronJobHandler := v1.NewCronJobHandler(cronJobService, jobManager)
	v2 := provider.ProvideV1Registrars(healthHandler, cronJobHandler)
	v1Handlers := router.NewV1Handlers(v2)
	engine := router.NewEngine(loggerLogger, configConfig, client, v1Handlers)
	httpServer := server.NewHttpServer(serverConfig, engine, loggerLogger)
	etcdConfig := provider.ProvideEtcdConfig(configConfig)
	clientv3Client, err := etcd.NewClient(etcdConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	appApp := app.NewApp(httpServer, loggerLogger, db, client, clientv3Client, jobManager)
	return appApp, nil
}
