// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/supuwoerc/gapi-server/internal/app"
	"github.com/supuwoerc/gapi-server/internal/config"
	"github.com/supuwoerc/gapi-server/internal/handler"
	"github.com/supuwoerc/gapi-server/internal/provider"
	"github.com/supuwoerc/gapi-server/internal/router"
	"github.com/supuwoerc/gapi-server/internal/server"
	"github.com/supuwoerc/gapi-server/pkg/database"
	"github.com/supuwoerc/gapi-server/pkg/logger"
	"github.com/supuwoerc/gapi-server/pkg/redis"
)

// Injectors from wire.go:

func WireApp() (*app.App, error) {
	viper := config.NewViper()
	configConfig := config.NewConfig(viper)
	serverConfig := provider.ProvideServerConfig(configConfig)
	logConfig := provider.ProvideLogConfig(configConfig)
	loggerLogger := logger.NewLogger(logConfig)
	redisConfig := provider.ProvideRedisConfig(configConfig)
	client, err := redis.NewClient(redisConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	healthHandler := handler.NewHealthHandler(loggerLogger)
	engine := router.NewEngine(loggerLogger, configConfig, client, healthHandler)
	httpServer := server.NewHttpServer(serverConfig, engine, loggerLogger)
	databaseConfig := provider.ProvideDBConfig(configConfig)
	db, err := database.NewConnection(databaseConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	appApp := app.NewApp(httpServer, loggerLogger, db, client)
	return appApp, nil
}
