// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/supuwoerc/gapi-server/internal/app"
	"github.com/supuwoerc/gapi-server/internal/config"
	"github.com/supuwoerc/gapi-server/internal/provider"
	"github.com/supuwoerc/gapi-server/pkg/database"
	"github.com/supuwoerc/gapi-server/pkg/logger"
	"github.com/supuwoerc/gapi-server/pkg/redis"
)

// Injectors from wire.go:

func WireCli() (*app.Cli, error) {
	viper := config.NewViper()
	configConfig := config.NewConfig(viper)
	logConfig := provider.ProvideLogConfig(configConfig)
	loggerLogger := logger.NewLogger(logConfig)
	databaseConfig := provider.ProvideDBConfig(configConfig)
	db, err := database.NewConnection(databaseConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	redisConfig := provider.ProvideRedisConfig(configConfig)
	client, err := redis.NewClient(redisConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	cli := app.NewCli(loggerLogger, db, client)
	return cli, nil
}
