// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/supuwoerc/gapi-server/internal/app"
	"github.com/supuwoerc/gapi-server/internal/config"
	"github.com/supuwoerc/gapi-server/internal/provider"
	"github.com/supuwoerc/gapi-server/pkg/database"
	"github.com/supuwoerc/gapi-server/pkg/etcd"
	"github.com/supuwoerc/gapi-server/pkg/logger"
	"github.com/supuwoerc/gapi-server/pkg/redis"
)

// Injectors from wire.go:

func WireCli() (*app.Cli, error) {
	viper := config.NewViper()
	bootstrapConfig := config.NewBootstrapConfig(viper)
	logConfig := provider.ProvideLogConfig(bootstrapConfig)
	loggerLogger := logger.NewLogger(logConfig)
	etcdConfig := provider.ProvideEtcdConfig(bootstrapConfig)
	client, err := etcd.NewClient(etcdConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	configConfig := config.NewConfig(viper, client, bootstrapConfig)
	databaseConfig := provider.ProvideDBConfig(configConfig)
	db, err := database.NewConnection(databaseConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	redisConfig := provider.ProvideRedisConfig(configConfig)
	redisClient, err := redis.NewClient(redisConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	discovery := etcd.NewDiscovery(client, etcdConfig, loggerLogger)
	cli := &app.Cli{
		Logger:    loggerLogger,
		DB:        db,
		Redis:     redisClient,
		Etcd:      client,
		Discovery: discovery,
	}
	return cli, nil
}
